server:
  port: 8789

cluster_mode: False

prometheus_url: http://localhost:9090

metrics: 
  - group: controlplane_billing
    detection_name: account_billing_balance
    metric: controlplane_billing_balance{has_paid_instance="1"}
    model: prophet
    sync_new_series_interval_seconds: 60
    window_size: 2h
    retraining_interval_minutes: 120
  - group: controlplane_billing
    detection_name: account_cu
    metric: controlplane_instance_monthly_cu{payment="paid", node="cn-hangzhou.10.1.47.178"}
    model: prophet
    sync_new_series_interval_seconds: 60
    window_size: 2h
    retraining_interval_minutes: 120


