apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app: detection-engine
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8789
  type: NodePort
  selector:
    app: detection-engine
