apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: detection-engine-monitor
spec:
  endpoints:
    - port: 80
      interval: 60s
  selector:
    matchLabels:
      app: detection-engine
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }} # update namespace to where the service is deployed
