apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ template "configmap.data-digest" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app: detection-engine
data:
  config.yaml: {{ include "configmap.data" . | b64enc }}